-- Compensate V11 without changing its checksum or Flyway history.
-- Restore only the exact text introduced by V11; preserve later custom edits.
-- Safe both after an existing V11 deployment and on a fresh database.
UPDATE message_template SET body = $old$MNET+. {categories}. One screenshot each. I'll wait.$old$ WHERE event_type = 'VOTE_BRIEFING' AND team = 'niki' AND variant = 1 AND body = $new$MNET+. {categories}. One save each original certificate. I'll wait.$new$;
UPDATE message_template SET body = $old$Today's categories: {categories}. Vote on MNET+, screenshot each, send them. I'll be right here.$old$ WHERE event_type = 'VOTE_BRIEFING' AND team = 'sunghoon' AND variant = 2 AND body = $new$Today's categories: {categories}. Vote on MNET+, save each original certificate, send them. I'll be right here.$new$;
UPDATE message_template SET body = $old$Open MNET+. Vote in {categories}. One screenshot per category. You've got this.$old$ WHERE event_type = 'VOTE_BRIEFING' AND team = 'sunghoon' AND variant = 1 AND body = $new$Open MNET+. Vote in {categories}. One original certificate per category. You've got this.$new$;
UPDATE message_template SET body = $old$No stress, mate. MNET+, these categories: {categories}. Screenshot each one and we're sorted.$old$ WHERE event_type = 'VOTE_BRIEFING' AND team = 'jake' AND variant = 2 AND body = $new$No stress, mate. MNET+, these categories: {categories}. Save the original certificate for each one and we're sorted.$new$;
UPDATE message_template SET body = $old$Hey, whenever you're ready: pop open MNET+ and vote in {categories}. Grab a screenshot of each and send them over. Easy as.$old$ WHERE event_type = 'VOTE_BRIEFING' AND team = 'jake' AND variant = 1 AND body = $new$Hey, whenever you're ready: pop open MNET+ and vote in {categories}. Grab an original certificate of each and send them over. Easy as.$new$;
UPDATE message_template SET body = $old$MNET+ time. Categories: {categories}. One screenshot per category, no category left behind. Leader's orders.$old$ WHERE event_type = 'VOTE_BRIEFING' AND team = 'jungwon' AND variant = 2 AND body = $new$MNET+ time. Categories: {categories}. One original certificate per category, no category left behind. Leader's orders.$new$;
UPDATE message_template SET body = $old$Here's the plan: open MNET+, vote in {categories}, screenshot each one and send them in. You've survived harder things. Like waiting for the comeback.$old$ WHERE event_type = 'VOTE_BRIEFING' AND team = 'jungwon' AND variant = 1 AND body = $new$Here's the plan: open MNET+, vote in {categories}, save the original certificate for each one and send them in. You've survived harder things. Like waiting for the comeback.$new$;
UPDATE message_template SET body = $old$Hiii! Open MNET+ and vote in {categories}. I can't wait to see your screenshots, one for every category!$old$ WHERE event_type = 'VOTE_BRIEFING' AND team = 'sunoo' AND variant = 2 AND body = $new$Hiii! Open MNET+ and vote in {categories}. I can't wait to see your original certificates, one for every category!$new$;
UPDATE message_template SET body = $old$Let's go vote on MNET+! Today's categories: {categories}. Send me a screenshot for each one and you'll make my whole day!$old$ WHERE event_type = 'VOTE_BRIEFING' AND team = 'sunoo' AND variant = 1 AND body = $new$Let's go vote on MNET+! Today's categories: {categories}. Send me an original certificate for each one and you'll make my whole day!$new$;
UPDATE message_template SET body = $old$Strategy for today: MNET+, categories {categories}. Cover every one, capture each result, box the proofs. Clean execution.$old$ WHERE event_type = 'VOTE_BRIEFING' AND team = 'jay' AND variant = 2 AND body = $new$Strategy for today: MNET+, categories {categories}. Cover every one, save each original certificate, box the proofs. Clean execution.$new$;
UPDATE message_template SET body = $old$Race plan: open MNET+ and run these categories: {categories}. One screenshot of each as your telemetry, then send them all.$old$ WHERE event_type = 'VOTE_BRIEFING' AND team = 'jay' AND variant = 1 AND body = $new$Race plan: open MNET+ and run these categories: {categories}. One original certificate of each as your telemetry, then send them all.$new$;
UPDATE message_template SET body = $old$Time to vote. Open MNET+ and vote in {categories}. Then send a screenshot for each category.$old$ WHERE event_type = 'VOTE_BRIEFING' AND team = 'default' AND variant = 1 AND body = $new$Time to vote. Open MNET+ and vote in {categories}. Then send an original certificate for each category.$new$;
UPDATE message_template SET body = $old$Lap {lap}. {categories}. I'll wait for you.$old$ WHERE event_type = 'DAILY_REMINDER' AND team = 'niki' AND variant = 1 AND body = $new$Reminder {lap}. {categories}. I'll wait for you.$new$;
UPDATE message_template SET body = $old$Lap {lap} is open. Still missing: {categories}. One screenshot each. You've got this.$old$ WHERE event_type = 'DAILY_REMINDER' AND team = 'sunghoon' AND variant = 1 AND body = $new$Reminder {lap}. Still missing: {categories}. One save each original certificate. You've got this.$new$;
UPDATE message_template SET body = $old$Hey, no rush... well, a little rush. Lap {lap}'s open and {categories} is still waiting. Votes, screenshots, done. Easy.$old$ WHERE event_type = 'DAILY_REMINDER' AND team = 'jake' AND variant = 1 AND body = $new$Hey, no rush... well, a little rush. Reminder {lap}: {categories} is still waiting. Votes, original certificates, done. Easy.$new$;
UPDATE message_template SET body = $old$I'm not asking twice. Okay, I am, but only because I care. {categories}, MNET+, screenshots. Go.$old$ WHERE event_type = 'DAILY_REMINDER' AND team = 'jungwon' AND variant = 2 AND body = $new$I'm not asking twice. Okay, I am, but only because I care. {categories}, MNET+, original certificates. Go.$new$;
UPDATE message_template SET body = $old$Lap {lap}. Still open: {categories}. Here's the plan: vote, screenshot, send. You've done harder things today. Like opening this notification.$old$ WHERE event_type = 'DAILY_REMINDER' AND team = 'jungwon' AND variant = 1 AND body = $new$Reminder {lap}. Still open: {categories}. Here's the plan: vote, save the original certificate, send. You've done harder things today. Like opening this notification.$new$;
UPDATE message_template SET body = $old$Lap {lap}! I'm still waiting for your proof in {categories} and I saved you a spot on the podium!$old$ WHERE event_type = 'DAILY_REMINDER' AND team = 'sunoo' AND variant = 1 AND body = $new$Reminder {lap}! I'm still waiting for your proof in {categories} and I saved you a spot on the podium!$new$;
UPDATE message_template SET body = $old$Lights out and away we go. {phase} is live. Plan A: vote, screenshot, send.$old$ WHERE event_type = 'LIGHTS_OUT' AND team = 'jay' AND variant = 1 AND body = $new$Lights out and away we go. {phase} is live. Plan A: vote, save the original certificate, send.$new$;
UPDATE message_template SET body = $old$Box this lap, not the next one. Missing proofs: {categories}. Votes in, screenshots captured, clean execution.$old$ WHERE event_type = 'DAILY_REMINDER' AND team = 'jay' AND variant = 2 AND body = $new$Time to check your proofs. Missing proofs: {categories}. Votes in, original certificates saved, clean execution.$new$;
UPDATE message_template SET body = $old$Lap {lap} delta: no proof on board for {categories}. Vote on MNET+, send the screenshots, gap closed.$old$ WHERE event_type = 'DAILY_REMINDER' AND team = 'jay' AND variant = 1 AND body = $new$Reminder {lap} delta: no proof on board for {categories}. Vote on MNET+, send the original certificates, gap closed.$new$;
UPDATE message_template SET body = $old$Your proof is still missing for {categories}. Vote on MNET+ and upload it to complete the lap.$old$ WHERE event_type = 'DAILY_REMINDER' AND team = 'default' AND variant = 2 AND body = $new$Your proof is still missing for {categories}. Vote on MNET+ and upload it to complete your checklist.$new$;
UPDATE message_template SET body = $old$Lap {lap} is open. Still to vote on MNET+: {categories}. Send a screenshot for each.$old$ WHERE event_type = 'DAILY_REMINDER' AND team = 'default' AND variant = 1 AND body = $new$Reminder {lap}. Still to vote on MNET+: {categories}. Send an original certificate for each.$new$;
